spring:
  pulsar:
    client:
      service-url: pulsar://localhost:6650

app:
  pulsar:
    command-topic: "persistent://public/default/service-b.commands"
    response-topic: "persistent://public/default/service-b.responses"
    compensate-topic: "persistent://public/default/service-b.compensate"
