spring:
  pulsar:
    client:
      service-url: pulsar://localhost:6650

app:
  pulsar:
    command-topic: "persistent://public/default/service-a.commands"
    response-topic: "persistent://public/default/service-a.responses"
    compensate-topic: "persistent://public/default/service-a.compensate"
