spring:
  pulsar:
    client:
      service-url: pulsar://localhost:6650
    consumer:
      subscription:
        name: serviceA
    defaults:
      type-mappings:
        - messageType: com.example.model.CommandMessage
          schema-info:
            schema-type: JSON
#        - messageType: com.example.model.TagRequest
#          schema-info:
#            schema-type: JSON
        - messageType: com.example.model.ReplyMessage
          schema-info:
            schema-type: JSON

app:
  pulsar:
    command-topic: "persistent://public/default/service-a.commands"
    response-topic: "persistent://public/default/service-a.responses"
    compensate-topic: "persistent://public/default/service-a.compensate"
