spring:
  pulsar:
    producer:
      topic-name1: adm-plain-topic
      topic-name2: adm-raw-topic
    consumer:
      subscription:
        name: my-subscription
    defaults:
      type-mappings:
        - messageType: com.example.model.OrchestrationResponse
          schema-info:
            schema-type: JSON
        - messageType: com.example.model.CommandMessage
          schema-info:
            schema-type: JSON
        - messageType: com.example.model.ReplyMessage
          schema-info:
            schema-type: JSON