# Non-Pulsar environment properties for DEV profile (apps in Docker network)
# Pulsar connection is configured in application-dev.yml
service.a.url=http://service-a:8080/processA
service.a.compensate.url=http://service-a:8080/compensateA
service.b.url=http://service-b:8080/processB
service.b.compensate.url=http://service-b:8080/compensateB
