# Non-Pulsar environment properties for LOCAL profile (apps on host)
# Pulsar connection is configured in application-local.yml
service.a.url=http://localhost:8081/processA
service.a.compensate.url=http://localhost:8081/compensateA
service.b.url=http://localhost:8082/processB
service.b.compensate.url=http://localhost:8082/compensateB
